cloud:
 aws:
  region:
    static: ap-south-1
     auto:false
    use-default-aws-region-chain: true
    stack: false
    stack.auto: false
  credentials:
     access-key: AKIAQYPJEIKTA5MGDCQC
     secret-key: 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 
  end-point:
    uri:https://sqs.ap-south-1.amazonaws.com/052565394086/Swati-queue
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error