cloud:
  aws:
    credentials:
      access-key: AKIAQYPJEIKTLIHOMEHU 
      secret-key: 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 
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: s3deqode


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

